# 站点配置

# 导入主题
theme: jekyll-theme-chirpy

# 站点基础设置
url: 'https://dashenxian.github.io'
baseurl: ''
lang: zh-CN                            # _data/locales 文件夹中同名文件
timezone: Asia/Shanghai

# jekyll SEO 标签设置 › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
title: xiaoshenxian                        # the main title
tagline: Blog site of xiaoshenxian         # it will display as the sub-title
description: >-                        # used by seo meta and the atom feed
  小神仙的博客。.NET/C#/WinUI/MAUI/WPF Windows

# 文章设置
author: 小神仙
post_author: 小神仙
description: 小神仙，.NET/Silverlight/Web 开发者
mail: 123880321@qq.com
about: .NET and Web Developer

# 社交账号设置
github:
  username: dashenxian
  link: https://github.com/dashenxian
facebook:
  username:
twitter:
  username:
stackoverflow:
  link:

social:
  name:
  email:
  links:
    # The first element serves as the copyright owner's link
    - https://github.com/dashenxian

# 访问追踪
analytics:
  google:
  cnzz:
disqus:
  name:
  url:
gitment:
  owner:
  client_id:
  client_secret:
  repo:
leancloud:
  appid:
  appkey:

# 外观设置
# Prefer color scheme setting.
#
# Note: Keep empty will follow the system prefer color by default,
# and there will be a toggle to switch the theme between dark and light
# on the bottom left of the sidebar.
#
# Available options:
#
#     light  - Use the light color scheme
#     dark   - Use the dark color scheme
#
theme_mode:   # [light|dark]

# The CDN endpoint for images.
# Notice that once it is assigned, the CDN url
# will be added to all image (site avatar & posts' images) paths starting with '/'
#
# e.g. 'https://cdn.com'
img_cdn:

logo: /assets/img/logo.png
icon: /favicon.ico
avatar:
  img:
  alt:
  url:
  hint:
license:
  img: /assets/img/by-nc-sa.svg

# boolean type, the global switch for ToC in posts.
toc: true

## 分页设置
excerpt_separator: ---
paginate: 30
per_page: 30
paginate_path: "/blog/page:num/"
collections:
  articles:
    output: true

# ------------ The following options are not recommended to be modified ------------------

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:   # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order


defaults:
  -
    scope:
      path: '_posts'          # An empty string here means all files in the project
      type: posts
    values:
      layout: post
      author: "小神仙"
      comments: true    # Enable comments in posts.
      toc: true         # Display TOC column in posts.
      # DO NOT modify the following parameter unless you are confident enough
      # to update the code of all other post links in this project.
      permalink: "/post/:title"
  -
    scope:
      path: _articles
      type: "articles"
    values:
      layout: "post"
      comments: false
      permalink: "/article/:title"
  -
    scope:
      path: ''
      type: tabs             # see `site.collections`
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - '*.gem'
  - '*.gemspec'
  - tools
  - docs
  - README.md
  - LICENSE
  - gulpfile.js
  - node_modules
  - package*.json

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
